### ISSUE TITLE
FM v6 is coming soon

### ISSUE THREAD

**Issue by JaffaKetchup** [TimBaumgart/flutter_map_polywidget#1]
The next version of flutter_map is coming soon, with breaking changes for all users and plugins!

Expected CHANGELOG: https://github.com/fleaflet/flutter_map/blob/release-prep/CHANGELOG.md
Likely to be merged PR with significant impacts: fleaflet/flutter_map#1615
Release prep PR: fleaflet/flutter_map#1632
New documentation (path liable to change): https://docs.fleaflet.dev/v/v6-1
Expected migration instructions, suitable for most users: https://docs.fleaflet.dev/v/v6-1/getting-started/migrating-to-v6
List of commits since v5 (more to come): https://github.com/fleaflet/flutter_map/compare/v5.0.0...master

**Comment by TimBaumgart** [comment]
Thanks for the information @JaffaKetchup! Since my package is relatively small, there is not much to do here. Is it possible for me to publish a version to pub.dev before FM v6 is actualliy published there or do I have to wait for that? What is the best practice?

**Comment by JaffaKetchup** [comment]
Hi @TimBaumgart,

I imagine there'll be a few things to do like changing the layer to use a `MobileLayerTransformer`, for example.

As the latest FM prerelease is relatively outdated now (we're not planning on another one), and you can't publish a package that depends on a git repo, I'd say the best thing to do is just make sure you're ready. Maybe make a PR that's ready to merge and publish once v6 is released.

(If there was a recent prerelease, the best thing to do would be to make a prerelease for your package as well.)

**Comment by TimBaumgart** [comment]
fyi: I migrated to the current master of flutter_map in https://github.com/TimBaumgart/flutter_map_polywidget/tree/v6-prep and will merge and publish it as soon as v6.0.0 gets released.

**Comment by JaffaKetchup** [comment]
Everything is in the master branch ready to go now, and the release is coming very very soon!

**Comment by TimBaumgart** [comment]
v1.0.0 for this package now supports flutter_map v6.0.0 and was published to pub.dev
