### ISSUE TITLE
Box Constraints

### ISSUE THREAD

**Issue by Josh-Dovey** [TimBaumgart/flutter_map_polywidget#4]
Hi, 

My PolyWidgets are not resizing. I've added constraints to the PolyWidget, like the docs have suggested, but the PolyWidget still reflects the dimensions of 'widthInMeters' and 'heightInMeters'. Any ideas why this is happening?

Here is my code:
![code](https://github.com/TimBaumgart/flutter_map_polywidget/assets/69112686/123cc561-d133-4774-bf49-3ae9209fe735)

And here is an example of the PolyWidget and different zoom levels:
Zoom 18
![Screenshot 2023-10-23 at 09 11 35](https://github.com/TimBaumgart/flutter_map_polywidget/assets/69112686/1379db8d-5d0d-47ab-949d-24309ec9735d)

Zoom 13
![Screenshot 2023-10-23 at 09 12 08](https://github.com/TimBaumgart/flutter_map_polywidget/assets/69112686/a16337cb-854c-4c80-bcd3-04d9fd3d2021)

The desired behaviour is that when zoomed out, the PolyWidget doesn't shrink and remains at a specific height and width. And when zoomed in, the PolyWidget does not expand and remains at a specific height and width. Any ideas/suggestions would be greatly appreciated.

Thanks in advance, and thanks for all the work on this package.

**Comment by TimBaumgart** [comment]
Hi, thanks for reporting the issue!

What you are seeing is the intended behaviour. The parameters `widthInMeters` and `heightInMeters` define the actual size on your map. The parameter `constraints` just lets you define the size of your `child`. This prevents layout issues when zooming too far in or out.

I will think about possible solutions for your desired behavour and get back to you later :) One might be to set `widthInMeters` and `heightInMeters` to the size desired size when zoomed out and scale the child with Transform.scale() using the current zoom level.

**Comment by Josh-Dovey** [comment]
Thanks for your suggestion. I've wrapped my GestureDetector in a Transform.scale and the PolyWidget scales great. The issue with this approach is that I need to recreate the PolyWidget on each map event. This causes some performance issues.

Instead, I've opted to use a dart map, where the key is the zoom level and the value holds the int I use for `widthInMeters`and `heightInMeters`. Along with some logic to tell the map when to recreate the PolyWidget each time a new zoom level is reached, greatly reducing the amount of times the PolyWidget is recreated. It all depends on what you prefer though, if you prefer performance over visuals or vice versa.

A new feature to allow for scaling on a PolyWidget would be nice. You could provide users with two options. 

1. A `scale` bool parameter along with a 'scaleWeight' int parameter that affects how much the element scales. - This approach could be for users that want a more visually appealing scale PolyWidget.
2. A `dimensionMap` Map parameter where the key is the zoom level and value is the dimensions they desire the PolyWidget to use. - This approach could be for users that want a more performant scale PolyWidget.

I look forward to seeing the solutions you come up with. Thanks.

**Comment by TimBaumgart** [comment]
Sounds great, thanks for the hints. I will look into it.
